// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXLtAmAx60V3zU1atVL7rb0P6ApRb4-G0',
    appId: '1:789995810582:web:81f6f933dfc8722d576a37',
    messagingSenderId: '789995810582',
    projectId: 'list-training-20cbc',
    authDomain: 'list-training-20cbc.firebaseapp.com',
    storageBucket: 'list-training-20cbc.appspot.com',
    measurementId: 'G-ZQYTPWN92J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQu7I7iSDYWcGe7JL9c1cW7pI_hREygGk',
    appId: '1:789995810582:android:b318ef62d57f2d81576a37',
    messagingSenderId: '789995810582',
    projectId: 'list-training-20cbc',
    storageBucket: 'list-training-20cbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaTcySAqW2jDYrNQaoTR8u3U0xJjqJzkc',
    appId: '1:789995810582:ios:4244a33acc1a27ab576a37',
    messagingSenderId: '789995810582',
    projectId: 'list-training-20cbc',
    storageBucket: 'list-training-20cbc.appspot.com',
    iosClientId: '789995810582-9d926em7dmhj9rggab1vhn09brs8peok.apps.googleusercontent.com',
    iosBundleId: 'com.example.listTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaTcySAqW2jDYrNQaoTR8u3U0xJjqJzkc',
    appId: '1:789995810582:ios:4244a33acc1a27ab576a37',
    messagingSenderId: '789995810582',
    projectId: 'list-training-20cbc',
    storageBucket: 'list-training-20cbc.appspot.com',
    iosClientId: '789995810582-9d926em7dmhj9rggab1vhn09brs8peok.apps.googleusercontent.com',
    iosBundleId: 'com.example.listTraining',
  );
}
