// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Hu9zQpOoat_WcD5Gwj4JE13K4BFdQvY',
    appId: '1:591577660072:web:31de1b13ff8adb563ca09d',
    messagingSenderId: '591577660072',
    projectId: 'list-taining',
    authDomain: 'list-taining.firebaseapp.com',
    storageBucket: 'list-taining.appspot.com',
    measurementId: 'G-R8GFLLEN4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hoVLzzGq9ycZXjb8WxgB6DawfkN4oPs',
    appId: '1:591577660072:android:10cdd46bef0fbbcf3ca09d',
    messagingSenderId: '591577660072',
    projectId: 'list-taining',
    storageBucket: 'list-taining.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9fO0JGWFyAZeJ4LkTbEdRMNqohZ6Iig',
    appId: '1:591577660072:ios:ee694a3f150e800d3ca09d',
    messagingSenderId: '591577660072',
    projectId: 'list-taining',
    storageBucket: 'list-taining.appspot.com',
    iosClientId:
        '591577660072-tc9cmtpc4hdbr93oqq5cehia4cpmn9b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.listTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP9fO0JGWFyAZeJ4LkTbEdRMNqohZ6Iig',
    appId: '1:591577660072:ios:ee694a3f150e800d3ca09d',
    messagingSenderId: '591577660072',
    projectId: 'list-taining',
    storageBucket: 'list-taining.appspot.com',
    iosClientId:
        '591577660072-tc9cmtpc4hdbr93oqq5cehia4cpmn9b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.listTraining',
  );
}
